language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp grunt-cli
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: M2/t9nj4XLuFMRP0MaVz/Hwvzp3tzEUZq1hSLrd4ZnzQla5xoP9xOepaC7e7IYWUy+QBT6X+BSvPd0wg1PVSdNgZOhASDTKfw6vfdsDWEem3NkAYJJoL/TQ0ED5/UyG7sXiYAQIjfc4a3VKzI5e05hKlwYUZKqHZCZcIT8ng6+c=
  on:
    tags: true
    repo: T1st3/opml-icon
